---
Author: Alyssa Ramirez
title: "Analysis of SARS-CoV2 snps"
output: html_document
date: "2024-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Setup

```{r Setup-chunk}
snp_file <- "data/sample_snp_data.csv"
sample_id <- "SRR12433063"
```

```{r Load necessary packages}
# Load required libraries and source the function

library(ggplot2)
source("code/functions/SNP_analyzation.R")
```

## Project description
In this project, we analyze a dataset of single nucleotide polymorphisms to 
investigate genetic variation in multiple genome samples. The analysis focuses 
on extracting data from a specific sample, visualizing SNP quality scores, and
generating different types of figures to demonstrate the results of each
genome.

```{r subet-data}
# Pass only the snp_file and sample_id arguments
single_sample_data <- subset_snp_data(file_path = snp_file,
                                  sample_id = sample_id)
# Create a csv file for subsetted data
output_file <- paste0("data/subset_snp_data", sample_id, ".csv")
write.csv(single_sample_data, file = output_file, row.names = FALSE)

# Confirmation message
cat("subset file saved as:" , output_file)
```

```{r snp-scatterplot, echo=FALSE, message=FALSE,warning=FALSE}
# Scatterplot of SNP quality scores
scatter_plot <- ggplot(single_sample_data, aes(x = pos, y = qual)) +
  geom_point(alpha = 0.6) +
  labs(
    title = paste("SNP quality scores by position for sample", sample_id),
    x = "Position in Genome",
    y = "SNP Quality Score"
    ) 

```




